#:schema https://developers.openai.com/codex/config-schema.json

# https://developers.openai.com/codex/config-reference
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
model_supports_reasoning_summaries = true
model_verbosity = "high"
hide_agent_reasoning = false
show_raw_agent_reasoning = true
approval_policy = "on-request"
personality = "pragmatic"
sandbox_mode = "workspace-write"

[history]
persistence = "save-all"

[sandbox_workspace_write]
network_access = true
writable_roots = [
    "/Users/vinta/.codex/skills",
    "/Users/vinta/Projects",
    "/usr/local/hal-9000",
]

[features]
shell_snapshot = true
unified_exec = true
multi_agent = true
