- name: Install Go
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - go
    - dep

- name: Create $GOPATH directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/Projects/oh-my-go"

- name: Enable Go environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/go/files/go_profile
  when: ansible_env.SHELL == "/bin/zsh"
